import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Bottomplayer from '../components/Bottomplayer'
import Navbar from '../components/Navbar'
import Sidebar from '../components/Sidebar'
import Pages from '../components/Pages'


const pages = {
  display:"flex",
  // border:"1px solid red",
  width:"99%"
  
}

export default function Home() {
  return (
    <div className={styles.container} style={{background:"black"}}>
      <Head>
        <title>Spotify - Web Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <div style={pages}>
      <Sidebar/>
      <Pages/>
      </div>

      <Bottomplayer/>
      
    </div>
  )
}
